### ISSUE TITLE
generates "required" for every occurrence

### ISSUE THREAD

**Issue by sebudde** [skolmer/i18n-tag-schema#5]
`i18n-tag-schema ./src` generates a required value for every occurrence, not only once.
i.e. using `{ i18n`Start` }` three times in the project generates `"required": ["Start","Start","Start"]` and this throws an npm error  `Error: schema is invalid: data.required should NOT have duplicate items`

**Comment by skolmer** [comment]
@sebudde good catch

**Comment by skolmer** [comment]
This has been fixed in [v1.5.0](https://github.com/skolmer/i18n-tag-schema/releases/tag/v1.5.0). Please read release notes for more details.
