### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by skolmer** [skolmer/i18n-tag-schema#8]
> Hi, fantastic work! would you consider supporting typescript? Currently it requires only JS files. Thanks!

by @tomitrescak
https://github.com/skolmer/vscode-i18n-tag-schema/issues/2

**Comment by skolmer** [comment]
There are no plans for typescript support yet but I will consider it.
The schema generator uses babylon to parse the JS code. It would require some work to get the AST of a typescript file.

**Comment by tomitrescak** [comment]
@skolmer the good news is that Typescript works out of the box for parsing the files;) what I meant by supporting typescript is to allow vscode to show translation strings also for typescript files (should be a simple change)

**Comment by skolmer** [comment]
I don't have a lot of experience with typescript. Can you provide a sample project that I can use for testing?

**Comment by MastroLindus** [comment]
I didn't test the parsing yet, but typescript's compiler exposes you an API with which you can traverse/visit all their AST already, it's described in their wiki/docs and it is also used in tslint as well. However I might suggest that the parsing might already work as @tomitrescak suggests.

I had a somehow related question about being able to configure the regex to match to allow the parsing to be done since I might want to wrap the i18n call in a function of mine and it would be useful to be able to specifiy a different name if I really want (even if at the problem I might call my function i18n as well)

**Comment by skolmer** [comment]
I don't expect this to work If you use full typescript syntax:

``` ts
i18nTagSchema('./src', '\\.tsx?$', './translation.schema.json', (output, type) => {
    console.log(output)
})
```

Using typescript compiler to build the AST should work but I'm not sure if the AST object structure is compatible to babylon's. If I can just generate the AST via ts compiler and use it as input for the existing traverse logic this could be easy to archive.
Could use some help here, PR's are welcome ;)

**Comment by MastroLindus** [comment]
I wanted to test it from the command line but I am getting an error 
`i18n-tag-schema ./src --filter \.tsx?$ --schema ./translation-schema.json`

if i try this it tells me that "Path must be a string, received undefined"

**Comment by skolmer** [comment]
Unfortunately there is a bug in the CLI that calls the key export as soon as the filter flag is used: https://github.com/skolmer/i18n-tag-schema/blob/master/cli/index.js#L81 
Key export requires an additional flag `-e | --export`

You can try `i18n-tag-schema ./src --filter \.tsx?$ -e .` or `i18n-tag-schema ./src --filter \.tsx?$ -e myfile.ts` if you want to export a specific file.
But now you will face another issue. The key export function has a hardcoded filter: https://github.com/skolmer/i18n-tag-schema/blob/master/lib/index.js#L490 :(

**Comment by skolmer** [comment]
@tomitrescak @MastroLindus I will close this issue and will work on these known limitations here: #9

**Comment by skolmer** [comment]
#16

**Comment by skolmer** [comment]
@tomitrescak @MastroLindus Just released v2.0.0 with custom preprocessor and typescript support. https://github.com/skolmer/i18n-tag-schema#preprocessors

**Comment by tomitrescak** [comment]
I'm wondering what will change, since even the old version was working flawlessly with Typescript ;) Good job anyways!

**Comment by skolmer** [comment]
The new preprocessor uses your locally installed typescript version. In the previous version babel did understand most of the typescript syntax but the new preprocesser now enables you to use all typescript features your installed typescript version supports.
